### ISSUE TITLE
sun.misc.Unsafe is a restricted class.

### ISSUE THREAD

**Issue by danielpazeto** [michelefi/gwtcon-websocket#2]
Hi @michelefi 
When I tried run that implementation of WebSockets the conlose log in eclipse give me the follow message **"java.lang.NoClassDefFoundError: sun.misc.Unsafe is a restricted class. Please see the Google  App Engine developer's guide for more details."**

I'm using Java 7, GWT2.7.0 and AppEngine 1.9.30.

The complete log here:[http://pastebin.com/hyu1HDkj](http://pastebin.com/hyu1HDkj)

Have you ever seen this issue/error?
I need so much of websocket server in my GWT project.

**Comment by michelefi** [comment]
Hi,
the problem isn't on the GWT side but that you tried to start the websocket
server (https://tyrus.java.net/) inside AppEngine. The JVM of AppEngine
have same limitation, for example doesn't allow to open custom TCP port.
The solution can be try to use managed vm environment (
https://cloud.google.com/appengine/docs/managed-vms/java/about-the-managed-vm-environment)
or check if AppEngine have a specific support for websocket or don't use
AppEngine

Il giorno mer 2 mar 2016 alle ore 23:16 danielpazeto <
notifications@github.com> ha scritto:

**Comment by danielpazeto** [comment]
Really, for some reason the AppEngine didn't work with your websocket implementation on my environment.
**Solution**: Then I changed my project to run in Tomcat7, copying **app/war** to **tomcat7/webapp/app**
**Tip**: If someone try use websocket with glassfish/grizzly jars and need download websocket-api.jar to the project to implement it, case raise an exception involving the _org.apache.tomcat.websocket.server.DefaultServerEndpointConfigurator_ raise. Try remove from _tomcat/lib_ all jars related with websocket, in my case I removed _tomcat7-websocket-api.jar_ e _websocket-api.jar_ from tomcat/lib.

Thanks so much @michelefi
